//------------------------------------------------------------------------------
// <auto-generated>
//     Bu dosyayi Visual Studio otomatik olarak yeniden olusturur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavSistemi
{
    public partial class Hata
    {
        protected global::System.Web.UI.WebControls.Literal ltHataBaslik;
        protected global::System.Web.UI.WebControls.Literal ltHataMesaj;
        protected global::System.Web.UI.WebControls.Literal ltAnaSayfa;
    }
}