//------------------------------------------------------------------------------
// <auto-generated>
//     Bu dosyayi Visual Studio otomatik olarak yeniden olusturur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSinavSistemi
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.Literal ltKayitOlBaslik;
        protected global::System.Web.UI.WebControls.Panel pnlMesaj;
        protected global::System.Web.UI.WebControls.Label lblMesaj;
        protected global::System.Web.UI.WebControls.Literal ltKullaniciAdi;
        protected global::System.Web.UI.WebControls.TextBox txtKullaniciAdi;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvKullaniciAdi;
        protected global::System.Web.UI.WebControls.Literal ltEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.Literal ltSifre;
        protected global::System.Web.UI.WebControls.TextBox txtSifre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSifre;
        protected global::System.Web.UI.WebControls.Literal ltSifreTekrar;
        protected global::System.Web.UI.WebControls.TextBox txtSifreTekrar;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSifreTekrar;
        protected global::System.Web.UI.WebControls.CompareValidator cvSifre;
        protected global::System.Web.UI.WebControls.Button btnKayit;
        protected global::System.Web.UI.WebControls.Literal ltZatenUye;
        protected global::System.Web.UI.WebControls.Literal ltGiris;
    }
}